Translate README to Chinese.
minio/minio-js-store-app pull request #26
Opened 2017-12-13 13:17 UTC by dingjs

Translate README to Chinese.

2017-12-26 10:56 UTC, dingjs commented
ping @yihuaf 
Thanks for you effort,These are the last PRs of the translation.

2017-12-27 02:37 UTC, yihuaf requested changes

2017-12-27 02:37 UTC, yihuaf commented on README_zh_CN.md
> +遍历`home.handlebars`中的`assets_url`，渲染商品图片的缩略图。为了简单起见，在本示例中我们没有用到数据库来存储商品的信息。如果你需要的话，你可以将这些信息存到你的数据库中。
遍历`home.handlebars`中的`assets_url`，渲染商品图片的缩略图 -> 遍历`home.handlebars`中的`assets_url`来渲染商品图片的缩略图

2018-01-02 18:45 UTC, yihuaf approved these changes

2018-01-03 08:28 UTC, merged